on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: remove zmq
        run:  sudo apt remove --purge --auto-remove libzmq5 libnorm1 libboost* cmake*
      - name: remove boost
        run: sudo rm -rf /usr/local/share/boost
      - name: cleanup
        run:  sudo apt-get clean; sudo apt-get autoclean
      - name: install zmq
        run:  sudo apt install libnorm1=1.5r6+dfsg1-6 libzmq5=4.2.5-1ubuntu0.2
      - name: install dependecies
        run:  sudo apt install build-essential cmake pkg-config libboost-all-dev=1.65.1.0ubuntu1 libssl-dev libsodium23=1.0.16-2 libsodium-dev=1.0.16-2 libpgm-dev=5.2.122~dfsg-2 libzmq3-dev=4.2.5-1ubuntu0.2 libunbound-dev libminiupnpc-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev libgtest-dev doxygen graphviz libpcsclite-dev libprotobuf-dev libnorm-dev=1.5r6+dfsg1-6 libpcsclite1
      - name: build
        run:  make dist-static
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/dist/bin/safex-wallet-cli
          asset_name: safex-wallet-cli-linux-${{ github.ref }}
          asset_content_type: application/binary